# File: guess-chatgpt-python.py
# Generated by ChatGPT, without any modification

import tkinter as tk
from tkinter import messagebox
import random

# Function to start a new game
def start_new_game():
    global secret_number, attempts
    secret_number = random.randint(1, 100)
    attempts = 0
    feedback_label.config(text="I've picked a number between 1 and 100. Try to guess it!")
    guess_entry.delete(0, tk.END)

# Function to process the player's guess
def check_guess():
    global attempts
    try:
        guess = int(guess_entry.get())
        attempts += 1

        if guess < secret_number:
            feedback_label.config(text="Too low!")
        elif guess > secret_number:
            feedback_label.config(text="Too high!")
        else:
            messagebox.showinfo("Congratulations!", f"You guessed it in {attempts} attempts!")
            start_new_game()

        if attempts >= max_attempts and guess != secret_number:
            messagebox.showinfo("Game Over", f"Sorry! The number was {secret_number}.")
            start_new_game()

    except ValueError:
        feedback_label.config(text="Please enter a valid number.")

    guess_entry.delete(0, tk.END)

# Initialize the game window
window = tk.Tk()
window.title("Guess the Number Game")
window.geometry("400x200")

# Set game variables
secret_number = random.randint(1, 100)
attempts = 0
max_attempts = 7

# Add UI components
feedback_label = tk.Label(window, text="I've picked a number between 1 and 100. Try to guess it!")
feedback_label.pack(pady=10)

guess_entry = tk.Entry(window, width=10)
guess_entry.pack(pady=5)

guess_button = tk.Button(window, text="Submit Guess", command=check_guess)
guess_button.pack(pady=5)

reset_button = tk.Button(window, text="Reset Game", command=start_new_game)
reset_button.pack(pady=5)

# Start the game
start_new_game()

# Start the GUI event loop
window.mainloop()